### ISSUE TITLE
The way to set human-readable IDs (something like URL slugs)

### ISSUE THREAD

**Issue by sgtpep** [rumpelsepp/pynote#16]
Example:
`$ note new todo "TODO"`
```
$ note list
ID  Title  Updated
--  -----  ---------
todo   TODO   3 seconds
```
`$ note edit todo`

As for me, it's nicer to deal with keywords or slugs than with some autogenerated number that has no meaning. Both system could co-exist, and latter could be optional.

**Comment by rumpelsepp** [comment]
That is implemented in the current v2.0.0 branch. Please note, that that branch will get rebased and the commit id will change.

Since every note has a `slug` property since 3d71530, we can use to match it against the cmdline.
Currently visible here: https://github.com/rumpelsepp/pynote/blob/5c80e908d46057975a96ff8174b77113b57d6c72/note#L207-L226; I will post a link to the final commit id when it's done.

**Comment by sgtpep** [comment]
Wow, thank you! I'll definitely try it.

**Comment by rumpelsepp** [comment]
you're welcome :) pynote 2.0.0 will be a complete rewrite. I refactored the whole mess into one file and dropped several dependencies. Currently not every command works, but it should not take to long 'till it is ready.

**Comment by rumpelsepp** [comment]
It is included in: https://github.com/rumpelsepp/pynote/commit/970504023136b43b1d01285a935fa4daf6c4aef4
